Repository habx/ui-core, pull requests merged in 2020-12, with the labels that each got.

#1535 APP-16686 Various UI fixes
  src/AutocompleteInput/useAutocomplete.ts
  src/Button/Button.style.ts
  src/Card/Card.style.ts
  src/ConfirmMenu/ConfirmMenu.tsx
  src/Menu/Menu.interface.ts
  src/Menu/Menu.stories.tsx
  src/Menu/Menu.style.ts
  src/Menu/Menu.tsx
  src/MenuLine/MenuLine.style.ts
  src/Modal/Modal.style.ts
  src/TabsBarMenuItem/TabsBarMenuItem.tsx
  src/Tag/Tag.stories.tsx
  src/TogglePanel/TogglePanel.interface.ts
  src/TogglePanel/TogglePanel.style.ts
  src/TogglePanel/TogglePanel.tsx
  src/TogglePanel/index.ts
  src/_internal/theme/useCurrentBackground.ts
  src/palette/palette.ts
  src/theme/theme.data.ts
  src/useThemeVariant.ts
Labels: habx-automerge

#1536 APP-16689 Remove transparence on secondary theme colors
  src/theme/theme.data.ts
Labels: habx-automerge

#1540 APP-16733: Export missing types for PRJ & CMS
  src/ThemeProvider/ThemeProvider.interface.ts
  src/ThemeProvider/index.ts
  src/index.ts
Labels: habx-automerge, habx-autorelease

#1541 Syncing dev with v5.0.1
  src/ThemeProvider/ThemeProvider.interface.ts
  src/ThemeProvider/index.ts
  src/index.ts
Labels: habx-automerge

#1545 Syncing dev with v5.0.2
  src/ActionBar/ActionBar.tsx
  src/IconButton/IconButton.tsx
  src/Menu/Menu.tsx
  src/_internal/theme/useHasColoredBackground.ts
  src/index.ts
  src/useCurrentBackground.ts
Labels: habx-automerge

#1550 APP-16767 Replace Button in Prompt Modal
  src/confirm/confirm.tsx
Labels: habx-autorelease

#1551 Syncing dev with v5.1.1
  src/confirm/confirm.tsx
Labels: habx-automerge

#1552 APP-16809: Missing exports for theme converter
  src/color.ts
  src/index.ts
  src/theme/index.ts
  typings/color-parse.d.ts
Labels: habx-autorelease

#1553 Syncing dev with v5.1.2
  src/color.ts
  src/index.ts
  src/theme/index.ts
  typings/color-parse.d.ts
Labels: habx-automerge

#1567 APP-16913: Rework SlideShow CSS override
  src/SlideShow/SlideShow.interface.ts
  src/SlideShow/SlideShow.tsx
  src/SlideShow/SlideShowNavigation.tsx
Labels: habx-automerge, habx-autorelease

#1573 APP-16917 radius > checkbox and icon-button have lost their radius
  src/Checkbox/Checkbox.style.ts
  src/IconButton/IconButton.style.ts
Labels: habx-autorelease

#1575 APP-16980: Pass props to DOM on ThemeProvider
  src/ThemeProvider/ThemeProvider.interface.ts
  src/ThemeProvider/ThemeProvider.tsx
Labels: habx-autorelease

#1576 Syncing dev with v5.3.1
  src/ThemeProvider/ThemeProvider.interface.ts
  src/ThemeProvider/ThemeProvider.tsx
Labels: habx-automerge

#1578 APP-17023: Slideshow redesign
  src/NavigationButton/NavigationButton.tsx
  src/NavigationDots/NavigationDots.style.ts
  src/RoundIconButton/RoundIconButton.interface.ts
  src/RoundIconButton/RoundIconButton.stories.tsx
  src/RoundIconButton/RoundIconButton.style.ts
  src/RoundIconButton/RoundIconButton.tsx
  src/RoundIconButton/index.ts
  src/SlideShow/SlideShow.stories.tsx
  src/SlideShow/SlideShow.style.ts
  src/SlideShow/SlideShowNavigation.tsx
  src/index.ts
Labels: habx-autorelease

#1598 APP-17118: Fix select element left alignement
  src/Select/Select.style.ts
Labels: habx-autorelease

#1599 APP-17120: Fix border-radius on toggle panel
  src/TogglePanel/TogglePanel.style.ts
Labels: habx-autorelease

#1600 Syncing dev with v5.5.1
  src/Select/Select.style.ts
Labels: habx-automerge

#1601 Syncing dev with v5.5.2
  src/TogglePanel/TogglePanel.style.ts
Labels: habx-automerge

#1602 APP-17136: Modal and LightBox should stop TogglePanel context propagation
  src/LightBox/LightBox.tsx
  src/Modal/Modal.tsx
  src/TogglePanel/TogglePanel.context.ts
  src/TogglePanel/TogglePanel.tsx
  src/_internal/withTogglePanelReset.tsx
Labels: habx-autorelease

#1607 APP-17204: Tab redesign
  src/Tab/Tab.style.ts
  src/Tab/Tab.tsx
  src/_storybook/withGrid.tsx
Labels: habx-autorelease

#1613 Syncing dev with v5.8.1
  src/Card/Card.interface.ts
  src/HeaderBar/HeaderBar.interface.ts
  src/Layout/Layout.interface.ts
  src/_internal/Banner/Banner.interface.ts
Labels: habx-automerge

#1616 APP-17353: Export ArrayInput types
  src/ArrayInput/ArrayInput.interface.ts
  src/ArrayInput/Item/Item.interface.ts
  src/ArrayInput/index.ts
  src/index.ts
Labels: habx-autorelease

#1617 Syncing dev with v5.8.2
  src/ArrayInput/ArrayInput.interface.ts
  src/ArrayInput/Item/Item.interface.ts
  src/ArrayInput/index.ts
  src/index.ts
Labels: habx-automerge
