Repository habx/ui-core, pull requests merged in 2020-07, with the labels that each got.

#1080 APP-12456 New Checkbox prop: small
  .circleci/config.yml
  src/Checkbox/Checkbox.interface.ts
  src/Checkbox/Checkbox.stories.tsx
  src/Checkbox/Checkbox.style.ts
  src/Checkbox/Checkbox.tsx
  src/RadioInput/RadioInput.style.ts
  src/withLabel/withLabel.tsx
Labels: habx-autorelease

#1086 Syncing dev with v3.14.1
  src/CardButton/CardButton.interface.ts
Labels: habx-automerge

#1092 APP-12686 Export ArrayInputItemComponentProps
  src/ArrayInput/ArrayInput.interface.ts
  src/ArrayInput/Item/Item.interface.ts
  src/ArrayInput/index.ts
  src/index.ts
Labels: habx-autorelease

#1093 Syncing dev with v3.14.2
  src/ArrayInput/ArrayInput.interface.ts
  src/ArrayInput/Item/Item.interface.ts
  src/ArrayInput/index.ts
  src/index.ts
Labels: habx-automerge

#1098 APP-12692: first draft of TextInputList
  src/TextInput/TextInput.interface.ts
  src/TextInput/TextInput.tsx
  src/TextInput/useAutocomplete.ts
  src/TextInputList/TextInputList.interface.ts
  src/TextInputList/TextInputList.stories.tsx
  src/TextInputList/TextInputList.style.ts
  src/TextInputList/TextInputList.tsx
  src/TextInputList/index.ts
  src/index.ts
Labels: habx-autorelease

#1101 APP-12742: fix SSR #habx-automerge
  src/_internal/useDisableScroll.ts
Labels: habx-automerge, habx-autorelease

#1102 Syncing dev with v3.15.1
  src/_internal/useDisableScroll.ts
Labels: habx-automerge

#1100 APP-12731: add button + ConfirmMenu
  src/ConfirmMenu/ConfirmMenu.interface.ts
  src/ConfirmMenu/ConfirmMenu.stories.tsx
  src/ConfirmMenu/ConfirmMenu.tsx
  src/ConfirmMenu/Menu.style.ts
  src/ConfirmMenu/index.ts
  src/TextInput/TextInput.stories.tsx
  src/TextInputList/TextInputList.stories.tsx
  src/TextInputList/TextInputList.style.ts
  src/TextInputList/TextInputList.tsx
  src/index.ts
Labels: habx-automerge

#1108 APP-12746: uniformize confirmMenu + tooltip
  src/ConfirmMenu/ConfirmMenu.interface.ts
  src/ConfirmMenu/ConfirmMenu.spec.tsx
  src/ConfirmMenu/ConfirmMenu.stories.tsx
  src/ConfirmMenu/ConfirmMenu.style.ts
  src/ConfirmMenu/ConfirmMenu.tsx
  src/Tooltip/Tooltip.interface.ts
  src/Tooltip/Tooltip.tsx
Labels: habx-automerge, habx-autorelease

#1109 APP-12605: fix breadcrumb colors
  package.json
  src/BreadcrumbItem/BreadcrumbItem.style.ts
Labels: habx-automerge, habx-autorelease

#1119 APP-12840: Navigation through text input is disable
  src/TextInput/useAutocomplete.ts
Labels: habx-autorelease

#1120 Syncing dev with v3.16.2
  src/TextInput/useAutocomplete.ts
Labels: habx-automerge

#1122 APP-12861: split TextInput & Autocomplete
  src/AutocompleteInput/AutocompleteInput.interface.ts
  src/AutocompleteInput/AutocompleteInput.stories.tsx
  src/AutocompleteInput/AutocompleteInput.tsx
  src/AutocompleteInput/index.ts
  src/AutocompleteInput/useAutocomplete.ts
  src/TextInput/TextInput.interface.ts
  src/TextInput/TextInput.stories.tsx
  src/TextInput/TextInput.tsx
  src/TextInputList/TextInputList.interface.ts
  src/TextInputList/TextInputList.stories.tsx
  src/TextInputList/TextInputList.tsx
  src/index.ts
Labels: habx-autorelease

#1123 APP-12873: allow to disable expansion panel item
  src/ExpansionPanelItem/ExpansionPanelItem.interface.ts
  src/ExpansionPanelItem/ExpansionPanelItem.style.ts
  src/ExpansionPanelItem/ExpansionPanelItem.tsx
Labels: habx-autorelease

#1129 Programmatically open elements of an `ArrayInput`
  src/ArrayInput/ArrayInput.interface.ts
  src/ArrayInput/ArrayInput.stories.tsx
  src/ArrayInput/ArrayInput.tsx
Labels: habx-autorelease
