Repository habx/ui-core, pull requests merged in 2020-10, with the labels that each got.

#1355 APP-14783: improve autocompleteInput
  src/AutocompleteInput/AutocompleteInput.interface.ts
  src/AutocompleteInput/AutocompleteInput.tsx
  src/AutocompleteInput/useAutocomplete.ts
Labels: habx-autorelease

#1357 APP-14839 Add 'spacing' prop to LightBox
  src/LightBox/LightBox.interface.ts
  src/LightBox/LightBox.style.ts
  src/LightBox/LightBox.tsx
Labels: habx-autorelease

#1364 APP-13932: improve tooltips
  src/Menu/Menu.tsx
  src/Tooltip/Tooltip.hooks.ts
  src/Tooltip/Tooltip.tsx
  src/_internal/useOnlyOpenedInstance.ts
Labels: habx-autorelease

#1365 APP-14971: notifications are behind modals
  src/notify/NotificationList.tsx
Labels: habx-autorelease

#1369 Syncing dev with v3.34.2
  src/notify/NotificationList.tsx
Labels: habx-automerge

#1376 APP-15139: LoaderBar
  src/LoadingBar/LoadingBar.stories.tsx
  src/LoadingBar/LoadingBar.tsx
  src/LoadingBar/index.ts
  src/index.ts
Labels: habx-automerge, habx-autorelease

#1385 Remove invalid reference on the `PhoneInput` component
  src/PhoneInput/PhoneInput.tsx
Labels: habx-autorelease

#1397 APP-15467: add loaderDots
  src/Button/Button.tsx
  src/Button/LoadingContainer.tsx
  src/LoaderDots/LoaderDots.interface.ts
  src/LoaderDots/LoaderDots.stories.tsx
  src/LoaderDots/LoaderDots.style.ts
  src/LoaderDots/LoaderDots.tsx
  src/LoaderDots/index.ts
  src/index.ts
Labels: habx-autorelease
