Repository habx/ui-core, pull requests merged in 2021-05, with the labels that each got.

#1835 APP-20755: Add toaster notifications of type `success`
  src/useGetColorFromType.ts
Labels: habx-autorelease

#1850 APP-21017: Fix menu position overflow
  src/DatePickerRange/DatePickerRange.style.ts
  src/Menu/Menu.utils.ts
Labels: automerge, autorelease

#1851 Syncing dev with v5.34.1
  src/DatePickerRange/DatePickerRange.style.ts
  src/Menu/Menu.utils.ts
Labels: automerge

#1866 APP-21262: Fix prompt type
  src/Provider/Provider.interface.ts
Labels: autorelease

#1867 Syncing dev with v5.35.1
  src/Provider/Provider.interface.ts
Labels: automerge
