Repository habx/ui-core, pull requests merged in 2021-03, with the labels that each got.

#1739 APP-19280: ci: fix publish
  .circleci/config.yml
  package.json
Labels: habx-automerge, habx-autorelease

#1741 APP-19048 card menu > component (re)design
  src/Card/Card.interface.ts
  src/Card/Card.style.ts
  src/Card/Card.tsx
  src/Icon/index.ts
  src/RoundIconButton/RoundIconButton.interface.ts
  src/color.ts
  src/index.ts
  src/notify/ToasterList.interface.ts
  src/notify/ToasterList.tsx
  src/useGetColorFromType.ts
Labels: habx-autorelease

#1748 APP-19340: Change hover style + Select inherit input
  src/Select/Select.interface.ts
  src/Select/Select.style.ts
  src/TextInput/TextInput.interface.ts
  src/TextInput/TextInput.style.ts
Labels: habx-autorelease

#1765 APP-19749: Fix icon in safari mobile
  src/RoundIconButton/RoundIconButton.style.ts
Labels: habx-automerge

#1758 APP-19312 Date Picker > design cleaning
  package-lock.json
  package.json
  src/DatePicker/DatePicker.stories.tsx
  src/DatePicker/DatePicker.tsx
  src/DatePicker/index.ts
  src/DatePickerRange/DatePickerPanel.tsx
  src/DatePickerRange/DatePickerRange.context.ts
  src/DatePickerRange/DatePickerRange.interface.ts
  src/DatePickerRange/DatePickerRange.stories.tsx
  src/DatePickerRange/DatePickerRange.style.ts
  src/DatePickerRange/DatePickerRange.tsx
  src/DatePickerRange/Day.tsx
  src/DatePickerRange/Month.tsx
  src/DatePickerRange/index.ts
  src/Menu/Menu.interface.ts
  src/Menu/Menu.stories.tsx
  src/Menu/Menu.utils.ts
  src/TogglePanel/TogglePanel.tsx
  src/index.ts
Labels: autoupdate

#1766 Syncing dev with v5.23.4
  src/RoundIconButton/RoundIconButton.style.ts
Labels: habx-automerge

#1767 APP-19694 Unable to hide the filter panel when organization filter is used
  src/SearchBar/SearchBar.tsx
  src/SearchBar/SearchPanel.tsx
Labels: habx-autorelease

#1768 Syncing dev with v5.23.5
  src/SearchBar/SearchBar.tsx
  src/SearchBar/SearchPanel.tsx
Labels: habx-automerge

#1773 APP-19904: Add card item component
  src/CardItem/CardItem.interface.ts
  src/CardItem/CardItem.stories.tsx
  src/CardItem/CardItem.style.ts
  src/CardItem/CardItem.tsx
  src/CardItem/index.ts
  src/index.ts
Labels: habx-autorelease

#1775 APP-19907: Fix font size
  src/CardItem/CardItem.style.ts
Labels: habx-automerge, habx-autorelease

#1777 APP-19913: Fix alertPanel padding
  src/AlertPanel/AlertPanel.interface.ts
  src/AlertPanel/AlertPanel.stories.tsx
  src/AlertPanel/AlertPanel.style.ts
  src/AlertPanel/AlertPanel.tsx
Labels: habx-autorelease

#1779 APP-19915: AlertPanel cleanup
  src/AlertPanel/AlertPanel.interface.ts
  src/AlertPanel/AlertPanel.stories.tsx
  src/AlertPanel/AlertPanel.style.ts
  src/AlertPanel/AlertPanel.tsx
Labels: habx-autorelease

#1783 APP-19954: Fix search panel event propagation
  src/SearchBar/SearchPanel.tsx
Labels: habx-automerge, habx-autorelease
