Repository habx/ui-core, pull requests merged in 2022-02, with the labels that each got.

#2212 APP-27253: Add infinite behaviour on loading bar
  src/LoadingBar/LoadingBar.interface.ts
  src/LoadingBar/LoadingBar.stories.tsx
  src/LoadingBar/LoadingBar.tsx
Labels: autorelease

#2222 APP-27614: fix(circleci): fix tsdoc-publish step
  .circleci/config.yml
Labels: automerge

#2225 APP-27730: fix(Slider): dark mode
  src/Slider/SliderDot/SliderDot.style.ts
  src/Slider/SliderDot/SliderDot.tsx
Labels: automerge, autorelease

#2226 APP-27844: Add expansion panel props in ArrayInputProps
  src/ArrayInput/ArrayInput.interface.ts
Labels: automerge, autorelease

#2227 APP-27851: Improve confirm modal
  src/Modal/Modal.interface.ts
  src/Modal/Modal.tsx
  src/Provider/Provider.context.ts
  src/Provider/Provider.interface.ts
  src/confirm/confirm.stories.tsx
  src/confirm/confirm.tsx
Labels: autorelease
