Repository habx/ui-core, pull requests merged in 2022-11, with the labels that each got.

#2447 APP-33489: fix(Storybook): fix title section
  src/Drawer/Drawer.stories.tsx
Labels: automerge

#2452 APP-33684: Fix casing of data attributes
  src/Slider/Slider.style.ts
  src/Slider/Slider.tsx
  src/Slider/SliderDot/SliderDot.style.ts
  src/Slider/SliderDot/SliderDot.tsx
  src/TabSelect/TabSelect.style.ts
  src/TabSelect/TabSelect.tsx
Labels: automerge

#2451 APP-33683: Use stable identifiers across server and client rendering
  src/_internal/buildUseOnlyOneInstanceOpened.tsx
  src/_internal/useUniqId.ts
Labels: automerge

#2457 APP-33734: Fix lost property `id` in the `withLabel` higher-order-component
  src/Checkbox/Checkbox.tsx
  src/RadioInput/RadioInput.tsx
  src/Toggle/Toggle.tsx
  src/withLabel/withLabel.tsx
Labels: automerge, autorelease

#2470 APP-34091: feat(Button): add size `tiny`
  src/Button/Button.interface.ts
  src/Button/Button.style.ts
  src/Button/Button.tsx
Labels: automerge, autorelease, front, front:lib

#2469 APP-34027: feature(ExpansionCard): introduce new component
  src/ExpansionCard/ExpansionCard.interface.ts
  src/ExpansionCard/ExpansionCard.stories.tsx
  src/ExpansionCard/ExpansionCard.style.ts
  src/ExpansionCard/ExpansionCard.tsx
  src/ExpansionCard/index.ts
  src/ExpansionPanel/ExpansionPanel.interface.ts
  src/ExpansionPanelItem/ControlledExpansionPanelItem.tsx
  src/ExpansionPanelItem/ExpansionPanelItem.interface.ts
  src/ExpansionPanelItem/ExpansionPanelItem.style.ts
  src/index.ts
Labels: automerge, autorelease, front, front:lib
